apiVersion: v1
kind: Namespace
metadata:
  annotations:
      argocd.argoproj.io/sync-options: Prune=false
  labels:
    kubernetes.io/metadata.name: prod
  name: prod
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
