apiVersion: v1
kind: Service
metadata:
  annotations:
      argocd.argoproj.io/sync-options: Prune=false
  name: guestbook-ui
  namespace: guestbook-locked
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
